"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](color_orange)\
$os\
[î‚°](bg:color_blue fg:color_orange)\
$directory\
[î‚°](fg:color_blue bg:color_green)\
$git_branch\
$git_status\
$git_state\
$git_commit\
[î‚°](fg:color_green bg:color_bg3)\
$docker_context\
$container\
$conda\
[î‚°](fg:color_bg3 bg:color_bg1)\
$gcloud\
$aws\
$asure\
[î‚´](fg:color_bg1)\
$line_break$character"""

# å³å´ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
right_format = """
$cmd_duration\
$c\
$python\
$rust\
$golang\
$nodejs\
$deno\
$java\
$haskell\
"""

# 2ã¤ã®å¡—ã‚Šã¤ã¶ã—å³ä¸‰è§’ã‚’è¡¨ç¤ºã™ã‚‹ç¶™ç¶šãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
continuation_prompt = 'â¯â¯ '

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#50c878'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "[ó°²](bg:color_orange fg:blue)"
Ubuntu = "ó°•ˆ"
NixOS = "î¡ƒ"

[username]
disabled = false
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_red"
format = '[$user]($style)'

[directory]
style = "fg:color_fg0 bg:color_blue"
format = "[$path]($style)"
read_only = "ï€£"
# ç¾åœ¨ã„ã‚‹gitãƒ¬ãƒã‚¸ãƒˆãƒªã®ãƒ«ãƒ¼ãƒˆã‚’åˆ‡ã‚Šæ¨ã¦ã‚‹ã‹ã©ã†ã‹(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ: true)
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "â€¦/"
home_symbol = '~'

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™"
"Music" = "ó°š"
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
".config" = "î˜•"
"INIAD2025" = "î¸’ "
"INIAD2026" = "î¸’ "
"spring" = "ğŸŒ¸"
"winter" = "â„ï¸"


[git_branch]
symbol = "ï˜"
format = '[$symbol $branch](fg:color_fg0 bg:color_green)'

[git_commit]
format = "[$tag](fg:$style bg:color_green)"
tag_disabled = false

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:$style bg:color_green)\) '

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
staged = '[++\($count\)](fg:green bg:color_green)'
format = '[($all_status$ahead_behind) ](fg:$style bg:color_green)'

[nodejs]
symbol = "îœ˜"
format = '[$symbol]($style) $version '
version_format = 'v${major}'
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']

[bun]
symbol = 'î¯'
format = '[$symbol]($style) '

[c]
symbol = "î˜"
format = '[$symbol]($style) $version '
version_format = 'v${major}'

[python]
symbol = "î˜†"
format = '[$symbol]($style) $version [$virtualenv](green) '
version_format = 'v${major}.${minor}'

[rust]
symbol = "î¨"
format = '[$symbol]($style) $version '
version_format = 'v${major}.${minor}'

[golang]
symbol = "î˜§"
format = '[$symbol]($style) $version '
version_format = 'v${major}.${minor}'

[php]
symbol = "î˜ˆ"
style = "bg:color_blue"
format = '$symbol $version'

[java]
symbol = "î‰–"
style = "bg:color_blue"
format = '[$symbol]($style) $version'
version_format = 'v${major}'

[kotlin]
symbol = "î˜´"
style = "bg:color_blue"
format = '$symbol $version'

[haskell]
symbol = "î˜Ÿ"
style = "bg:color_blue"
format = '$symbol $version'

[docker_context]
symbol = "ïŒˆ"
style = "bg:color_bg3"
format = '[[$symbol($context)](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[$symbol($environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[ ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = true

[memory_usage]
disabled = true
symbol = 'ó°›'
style = "bold dimmed fg:blue"
threshold = 10
format = "[$symbol$ram]($style)"

[character]
disabled = false
success_symbol = '[â¯](bold fg:color_green)'
error_symbol = '[â¯](bold fg:color_red)'
vimcmd_symbol = '[â®](bold fg:color_green)'
vimcmd_replace_one_symbol = '[â®](bold fg:color_purple)'
vimcmd_replace_symbol = '[â®](bold fg:color_purple)'
vimcmd_visual_symbol = '[â®](bold fg:color_yellow)'

[cmd_duration]
format = "[ó±«Œ $duration ]($style)"
