"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$os\
$directory\
[$git_branch$git_status$git_state$git_commit](fg:color_orange)\
$c$python$rust$golang$nodejs$deno$java$haskell\
$memory_usage\
$cmd_duration\
$line_break$character"""

# å³å´ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
# right_format = """
# """

# 2ã¤ã®å¡—ã‚Šã¤ã¶ã—å³ä¸‰è§’ã‚’è¡¨ç¤ºã™ã‚‹ç¶™ç¶šãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
continuation_prompt = 'â¯â¯ '

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#50c878'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
format = "[@$name]($style) "

[os.symbols]
Windows = "[ó°²](fg:blue)"
Ubuntu = "ó°•ˆ"
NixOS = "î¡ƒ"

[username]
disabled = false
show_always = false
style_user = "fg:color_fg0"
style_root = "fg:color_red"
format = '[$user]($style)'

[directory]
read_only = "ï€£"
truncation_length = 2
# ç¾åœ¨ã„ã‚‹gitãƒ¬ãƒã‚¸ãƒˆãƒªã®ãƒ«ãƒ¼ãƒˆã‚’åˆ‡ã‚Šæ¨ã¦ã‚‹ã‹ã©ã†ã‹(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ: true)
truncate_to_repo = true
truncation_symbol = "â€¦/"
home_symbol = '~'

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™"
"Music" = "ó°š"
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
".config" = "î˜•"
"INIAD2025" = "î¸’ "
"INIAD2026" = "î¸’ "
"spring" = "ğŸŒ¸"
"winter" = "â„ï¸"


[git_branch]
symbol = "î‚ "
format = '$symbol$branch'
truncation_length = 20

[git_commit]
tag_disabled = false
commit_hash_length = 4

[git_state]

[git_status]

[nodejs]
symbol = "îœ˜"
format = '$symbol$version '
version_format = 'v${major}'
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']

[bun]
symbol = 'î¯'
format = '[$symbol]($style) '

[c]
symbol = "î˜"
format = '[$symbol]($style)$version '
version_format = 'v${major}'

[python]
symbol = "î˜†"
format = '[$symbol]($style)$version[$virtualenv](green) '
version_format = 'v${major}.${minor}'

[rust]
symbol = "î¨"
format = '[$symbol]($style)$version '
version_format = 'v${major}.${minor}'

[golang]
symbol = "î˜§"
format = '[$symbol]($style)$version '
version_format = 'v${major}.${minor}'

[java]
symbol = "î‰–"
format = '[$symbol]($style)$version'
version_format = 'v${major}'

[haskell]
symbol = "î˜Ÿ"
format = '[$symbol$version]($style)'

[time]
disabled = true
time_format = "%R"
format = '[[ïº $time](fg:color_fg0 bg:color_bg1)]($style) '

[line_break]
disabled = false

[memory_usage]
disabled = false
symbol = 'ó°›'
style = "bold dimmed fg:blue"
threshold = 0
format = "[$symbol$ram]($style) "

[character]
disabled = false
success_symbol = '[â¯](bold fg:color_green)'
error_symbol = '[â¯](bold fg:color_red)'
vimcmd_symbol = '[â®](bold fg:color_green)'
vimcmd_replace_one_symbol = '[â®](bold fg:color_purple)'
vimcmd_replace_symbol = '[â®](bold fg:color_purple)'
vimcmd_visual_symbol = '[â®](bold fg:color_yellow)'

[cmd_duration]
format = "[ó±«Œ $duration ]($style)"
